### ISSUE TITLE
Attempt to renew a license nearing expiry was unsuccessful - will continue to use current license

### ISSUE THREAD

**Issue by masonearles** [reinzor/picovoice_ros#5]
## Expected behaviour

We are running Picovoice Rhino on a Jetson Xavier NX via the `picovoice_ros` node. Up until this morning it has worked very well for almost one month.

## Actual behaviour

As of today we are receiving the following error:

`[WARN] Attempt to renew a license nearing expiry was unsuccessful - will continue to use current license.`

Picovoice appears to be continuously attempting to reconnect which is causing gaps in the "listening" function which leads to missed detections.

**Comment by reinzor** [comment]
Hi thanks for the issue. What version are you using?

**Comment by masonearles** [comment]
Resolved here <https://github.com/Picovoice/picovoice/issues/446>.

**Comment by masonearles** [comment]
Resolved the issue [here](https://github.com/Picovoice/picovoice/issues/446). Thanks!

**Comment by reinzor** [comment]
👍 so this issue can be closed?

**Comment by masonearles** [comment]
Yes! Thank you.
